sudo: false

language: node_js
node_js:
  - "8"

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages

os: linux

env: ELM_VERSION=0.19.0

install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test@0.19.0-beta4

script:
  - elm-test
